### PR TITLE
Some improvements and a few updates on the snippets

### PR DESCRIPTION
**Pull request by srus**
Some improvements in the markup based on [HTML5 Boilerplate](https://github.com/h5bp/html5-boilerplate/blob/master/index.html) and [GitHub HTML Guidelines](https://github.com/styleguide/templates).

A new behaviour in some snippets, updating, adding and removing some of them.

### CODE REVIEW

**Comment by joshnh** [comment]
@srus Any reason you closed this?

**Comment by srus** [comment]
Yes, I thought there were so many commits for just one pull request and that maybe that was the reason because you didn't merge it... What do you think? I can reopen it again if you like or send new pull requests.

**Comment by joshnh** [comment]
Yeah, it was pretty big :D Just curious. Smaller parts would be easier for me.

**Comment by srus** [comment]
Definitely my fork has diverged so much that it's quite difficult for me to pick those changes that should be merged into your master branch. Maybe it's better if you cherry-pick from my branch those commits that would be interesting for you...

**Comment by joshnh** [comment]
Okay, thanks.

**Pull request closed without merging**
